---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-host-path
spec:
    replicas: 1
    selector:
      matchLabels:
          app: my-app
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: my-app
      spec:
        containers:
          - name: nginx
            image: quay.io/testing-farm/nginx:1.12
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi
            volumeMounts:
            - name: data
              mountPath: /files
        volumes:
          - name: data
            hostPath:
              path: /data_pod            
...
