---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector: 
    app:
        probes-app
  type: LoadBalancer
  loadBalancerIP: 1.1.1.1
  ports:
     - port: 80
       targetPort: 80
...
