---
apiVersion: v1
kind: Service
metadata:
  name: eis-service
spec:
  selector: 
    app:
        probes-app
  ports:
    - name: http   
      port: 80
      targetPort: 80
      protocol: TCP
  externalIPs:
    - 80.11.12.10
...
