---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  selector: 
    app:
        probes-app
  type: NodePort
  ports:
    - name: http   
      port: 80
      targetPort: 80
      protocol: TCP
...
